apiVersion: v1
kind: Namespace
metadata:
  name: vc
---
apiVersion: v1
kind: Service
metadata:
  name: motion
  namespace: vc
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: mdetect
    - port: 8082
      protocol: TCP
      targetPort: 8082
      name: mremote
  selector:
    app: motion
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: motion
  namespace: vc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: motion
    spec:
      containers:
        - name: motion
          securityContext:
            privileged: true
          image: vc-motion
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /dev/video0
            name: webcam
          - mountPath: /config
            name: config
          - mountPath: /home/nobody/motioneye/media
            name: media
          - mountPath: /home/nobody/motioneye/scripts
            name: scripts
          ports:
          - containerPort: 8081
          - containerPort: 8082
      volumes:
      - name: webcam
        hostPath:
          path: /dev/video0
          type: CharDevice
      - name: config
        hostPath:
          path: /root/appdata/motion/config
          type: Directory
      - name: media
        hostPath:
          path: /root/appdata/motion/media
          type: DirectoryOrCreate
      - name: scripts
        hostPath:
          path: /root/appdata/motion/scripts
          type: Directory
