#!/bin/bash

echo "Analyzing picture frame $1 ..." >> /home/nobody/motioneye/log/motion.log
FRAME=$1

if [ -z "$FACEBOX_URL" ]; then
    FACEBOX_URL="http://facebox.192.168.1.202.xip.io"
fi

curl -X POST -H "Content-Type: multipart/form-data; charset=utf-8" -H "Accept: application/json; charset=utf-8" -F "file=@$FRAME" $FACEBOX_URL/facebox/similar >> /home/nobody/motioneye/log/motion.log

